import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		includeSource: ["src/**/*.spec.ts"],
		include: ["tests/**/*.test.ts"],
		exclude: [...configDefaults.exclude, "tests/modules/**", "temp-test/**"],
		globals: true,
		environment: "node",
		setupFiles: ["tests/setup/vitest.setup.ts"],
		watch: false,
		coverage: {
			provider: "v8",
			reporter: ["text", "json", "html"],
			exclude: [
				"coverage/**",
				"dist/**",
				"mock/**",
				"temp-test/**",
				"tests/**",
				"**/*.d.ts",
				"**/templates/**",
				"build.js",
				"vitest.config.ts",
				"tsup.config.js",
				"src/templates/**",
				"src/shared/spinner.ts",
			],
		},
	},
	resolve: {
		alias: {
			"@core/": "/src/core/",
			"@application/": "/src/application/",
			"@infrastructure/": "/src/infrastructure/",
			"@interface/": "/src/interface/",
			"@configs/": "/src/configs/",
			"@templates/": "/src/templates/",
			"@schema/": "/src/schema/",
			"@mappings/": "/src/mappings/",
			"@pipeline/": "/src/pipeline/",
			"@pipeline": "/src/pipeline.ts",
			"@generators/": "/src/generators/",
			"@errors": "/src/errors/index.ts",
			"@errors/": "/src/errors/",
			"@errors/index": "/src/errors/index.ts",
			"@shared/": "/src/shared/",
			"@prompts/": "/src/prompts/",
		},
	},
});
